### ISSUE TITLE
[Request] Translate to Russian language

### ISSUE THREAD

**Issue by Rishats** [codestudiohq/laravel-totem#13]
Hello! I can translate some pages into Russian! Do you need this?

**Comment by roshangautam** [comment]
The only lang file we currently have is for messages. To be able to use proper translations we will have to use lang files for everything that should translatable including form field labels, placeholders and other text. I will be more than happy to review and merge any changes, if you are up for that.

**Comment by phuthoma** [comment]
Dear @roshangautam, 

I'll be quite happy to translate your module into Polish. Have you changed all hardcoded lines to translatables phrases and prepeared [en] translation file?
