### ISSUE TITLE
What happens to regular scheduled tasks?

### ISSUE THREAD

**Issue by mortenscheel** [codestudiohq/laravel-totem#24]
Hi.
I was a bit confused about the scope of this package. It wasn't clear to me that it would completely take over my schedule, and ignore scheduled tasks defined in app/Console/Kernel.php.

**Comment by roshangautam** [comment]
I understand the feeling but currently the only way is to move your scheduled tasks to dashboard. The whole point of using a dashboard is to be able to schedule commands from a web browser. I am trying to find a way where you can also use the traditional Laravel way of scheduling tasks along with totem. Stay tuned :)

**Comment by roshangautam** [comment]
@mortenscheel , Tasks can now be scheduled traditionally in addition from totem dashboard. Please update to the latest alpha. Don't forget to run `php artisan totem:assets` once you are done updating.

Thanks for the feedback and trying this package. Appreciate it.

**Comment by mortenscheel** [comment]
Awesome. Thanks.
