### ISSUE TITLE
command filter and easy import/export

### ISSUE THREAD

**Issue by vesper8** [codestudiohq/laravel-totem#36]
I just took my first look at your package. Great work on the UI and the level of customizability!

I think it would be nice to have an easy means of importing and exporting lists of scheduled commands. Otherwise it seems a bit awkward to design all your schedules on dev and then port them over to production. This is normally very straightforward when commands are committed to code but not so clear with your package. Yes you could use seeders.. or you could dump the 4 tables manually.. but it would be nice if this was built-in to the package

My 2nd suggestion is having some kind of "command filter" in a config file. Right now the drop-down includes all detected commands which in my app's case is a huge list of 70+ commands.. 95% of which would never be scheduled. It would be nice if there was an optional array of command filters in a totem.php config file where I could use wildcards for example:

```
return [
    'command-filters' => [
        'backup:*',
        'custom:*'
        'some:command'
    ],
]
```

**Comment by vesper8** [comment]
I've gone ahead and added the command filter functionality in my app.. here's the modifications I made

/config/totem.php:
```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Active Command Filter
    |--------------------------------------------------------------------------
    |
    | ...
    */

    'active_command_filter' => [
        'backup:*',
        'debugbar:clear',
    ],

];
```

TasksController:
```
    /**
     * Show the form for creating a new task.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        if (config('totem.active_command_filter') && count(config('totem.active_command_filter'))) {
            $activeCommands = [];
            $allCommands = Artisan::all();

            foreach ($allCommands as $command) {
                foreach (config('totem.active_command_filter') as $filter) {
                    if (fnmatch($filter, $command->getName())) {
                        $activeCommands[] = $command;
                    }
                }
            }
        } else {
            $activeCommands = Artisan::all();
        }

        return view('totem::tasks.form', [
            'task' => new Task,
            'commands' => collect($activeCommands)->sortBy(function ($command) {
                return $command->getDescription();
            }),
            'timezones' => timezone_identifiers_list(),
            'frequencies' => Totem::frequencies(),
        ]);
    }
```

**Comment by roshangautam** [comment]
Thanks @vesper8 . This looks useful. I will refactor and incorporate this in next release.

**Comment by vonec** [comment]
is this done ?

**Comment by roshangautam** [comment]
Command filter part of this issue is now available in new release. Thanks @qschmick.

**Comment by qschmick** [comment]
@vonec @vesper8 Just merged in the ability to import/export all tasks.

**Comment by vesper8** [comment]
thanks @qschmick !! that's great!
